### ISSUE TITLE
Issues Running Quantization on A10

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/text-generation-inference#206] opened 2023-04-19 17:14 UTC
I am seeing the following failures around bitsandbytes with `BUILD_EXTENSIONS=False`
```bash
{"timestamp":"2023-04-19T17:08:49.606067Z","level":"INFO","fields":{"message":"Args { model_id: \"chavinlo/alpaca-13b\", revision: None, sharded: None, num_shard: Some(1), quantize: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 1512, max_batch_size: 32, max_waiting_tokens: 20, port: 6018, shard_uds_path: \"/tmp/text-generation-server\", master_addr: \"localhost\", master_port: 29500, huggingface_hub_cache: Some(\"/data\"), weights_cache_override: None, disable_custom_kernels: false, json_output: true, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None }"},"target":"text_generation_launcher"}
{"timestamp":"2023-04-19T17:08:49.606372Z","level":"INFO","fields":{"message":"Starting shard 0"},"target":"text_generation_launcher"}
{"timestamp":"2023-04-19T17:08:51.913366Z","level":"ERROR","fields":{"message":"Error when initializing model\nTraceback (most recent call last):\n  File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n    sys.exit(app())\n  File \"/opt/conda/lib/python3.9/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n  File \"/opt/conda/lib/python3.9/site-packages/typer/core.py\", line 778, in main\n    return _main(\n  File \"/opt/conda/lib/python3.9/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n  File \"/opt/conda/lib/python3.9/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py\", line 58, in serve\n    server.serve(model_id, revision, sharded, quantize, uds_path)\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 135, in serve\n    asyncio.run(serve_inner(model_id, revision, sharded, quantize))\n  File \"/opt/conda/lib/python3.9/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 634, in run_until_complete\n    self.run_forever()\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n    self._run_once()\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n    handle._run()\n  File \"/opt/conda/lib/python3.9/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 104, in serve_inner\n    model = get_model(model_id, revision, sharded, quantize)\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py\", line 133, in get_model\n    return llama_cls(model_id, revision, quantize=quantize)\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py\", line 306, in __init__\n    raise ValueError(\"quantization is not available on CPU\")\nValueError: quantization is not available on CPU\n"},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2023-04-19T17:08:52.408673Z","level":"ERROR","fields":{"message":"Shard 0 failed to start:\n/opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.\n  warn(\"The installed version of bitsandbytes was compiled without GPU support. \"\nTraceback (most recent call last):\n\n  File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n    sys.exit(app())\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py\", line 58, in serve\n    server.serve(model_id, revision, sharded, quantize, uds_path)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 135, in serve\n    asyncio.run(serve_inner(model_id, revision, sharded, quantize))\n\n  File \"/opt/conda/lib/python3.9/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 647, in run_until_complete\n    return future.result()\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 104, in serve_inner\n    model = get_model(model_id, revision, sharded, quantize)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py\", line 133, in get_model\n    return llama_cls(model_id, revision, quantize=quantize)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py\", line 306, in __init__\n    raise ValueError(\"quantization is not available on CPU\")\n\nValueError: quantization is not available on CPU\n\n"},"target":"text_generation_launcher"}
{"timestamp":"2023-04-19T17:08:52.408710Z","level":"INFO","fields":{"message":"Shutting down shards"},"target":"text_generation_launcher"}
```

It seems the container can not find the GPU even though it is assigned one as seen below in the output of `describe po`
```bash
Containers:
  ml:
    Container ID:   containerd://53b79673ab1059dc4d514f6bccc54ad6fb94b2185b02ba5abe56da6f8d949a5b
    Image:          ghcr.io/huggingface/text-generation-inference:latest
    Image ID:       ghcr.io/huggingface/text-generation-inference@sha256:84d3f31e170cc733e86913787c968a5202515d2021bc18832cbc117a49f07dad
    Port:           6018/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 19 Apr 2023 13:06:14 -0400
      Finished:     Wed, 19 Apr 2023 13:06:16 -0400
    Ready:          False
    Restart Count:  4
    Limits:
      ephemeral-storage:  95551679100
      nvidia.com/gpu:     1
    Requests:
      ephemeral-storage:  95551679100
      nvidia.com/gpu:     1
    Liveness:             http-get http://:http/ delay=600s timeout=1s period=600s #success=1 #failure=3
    Readiness:            http-get http://:http/ delay=300s timeout=1s period=300s #success=1 #failure=3
    Environment:
      MODEL_ID:          chavinlo/alpaca-13b
      NUM_SHARD:         1
      QUANTIZE:          true
      PORT:              80
      BUILD_EXTENSIONS:  false
```

Here is the output of running `nvidia-smi` on the node
```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   27C    P0    57W / 300W |  17654MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

```

I was able to get past this error yesterday by disabling the build extensions which got me to the point where FlashLlama was throwing errors because quantization was not implemented. However today no dice. Am I doing something wrong?

**Comment by OlivierDehaene** [comment] 2023-04-19 17:51
This might have been an issue with the docker image. 
Can you try with the latest one? ghcr.io/huggingface/text-generation-inference:sha-6837b2e

**Comment by sam-h-bean** [comment] 2023-04-19 19:14
yeah one sec

**Comment by sam-h-bean** [comment] 2023-04-19 19:26
No dice @OlivierDehaene it seems something has changed since I was able to get past this point yesterday

**Comment by OlivierDehaene** [comment] 2023-04-19 19:52
I was able to run the following command on a A10 powered VM:

```shell
docker run --gpus "device=0" -p 8080:80 -v $PWD/data:/data  ghcr.io/huggingface/text-generation-inference:sha-6837b2e --model-id decapoda-research/llama-7b-hf --quantize
```

Are you sure you don't have another issue with your setup?

**Comment by sam-h-bean** [comment] 2023-04-19 20:19
I'm not sure I still just see 

```bash
{"timestamp":"2023-04-19T20:17:40.488749Z","level":"ERROR","fields":{"message":"Shard 0 failed to start:\n/opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.\n  warn(\"The installed version of bitsandbytes was compiled without GPU support. \"\nTraceback (most recent call last):\n\n  File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n    sys.exit(app())\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py\", line 58, in serve\n    server.serve(model_id, revision, sharded, quantize, uds_path)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 135, in serve\n    asyncio.run(serve_inner(model_id, revision, sharded, quantize))\n\n  File \"/opt/conda/lib/python3.9/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 647, in run_until_complete\n    return future.result()\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 104, in serve_inner\n    model = get_model(model_id, revision, sharded, quantize)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py\", line 133, in get_model\n    return llama_cls(model_id, revision, quantize=quantize)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/causal_lm.py\", line 306, in __init__\n    raise ValueError(\"quantization is not available on CPU\")\n\nValueError: quantization is not available on CPU\n\n"},"target":"text_generation_launcher"}
```

However I'm using bitsandbytes on a different pod on the same node and AMI

**Comment by sam-h-bean** [comment] 2023-04-19 20:34
Do you have any idea what else would be horrible wrong here?

I went back to the 0.5.0 and am seeing

```bash
{"timestamp":"2023-04-19T20:30:38.758543Z","level":"INFO","fields":{"message":"Args { model_id: \"decapoda-research/llama-7b-hf\", revision: None, sharded: None, num_shard: Some(1), quantize: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 1512, max_batch_size: 32, max_waiting_tokens: 20, port: 6018, shard_uds_path: \"/tmp/text-generation-server\", master_addr: \"localhost\", master_port: 29500, huggingface_hub_cache: Some(\"/data\"), weights_cache_override: None, disable_custom_kernels: false, json_output: true, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None }"},"target":"text_generation_launcher"}
{"timestamp":"2023-04-19T20:30:38.758781Z","level":"INFO","fields":{"message":"Starting shard 0"},"target":"text_generation_launcher"}
{"timestamp":"2023-04-19T20:30:40.794214Z","level":"ERROR","fields":{"message":"\"Error when initializing model\nTraceback (most recent call last):\n  File \\\"/opt/miniconda/envs/text-generation/bin/text-generation-server\\\", line 8, in <module>\n    sys.exit(app())\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/typer/main.py\\\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/click/core.py\\\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/typer/core.py\\\", line 778, in main\n    return _main(\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/typer/core.py\\\", line 216, in _main\n    rv = self.invoke(ctx)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/click/core.py\\\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/click/core.py\\\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/click/core.py\\\", line 760, in invoke\n    return __callback(*args, **kwargs)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/typer/main.py\\\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/cli.py\\\", line 55, in serve\n    server.serve(model_id, revision, sharded, quantize, uds_path)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/server.py\\\", line 135, in serve\n    asyncio.run(serve_inner(model_id, revision, sharded, quantize))\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/asyncio/runners.py\\\", line 44, in run\n    return loop.run_until_complete(main)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/asyncio/base_events.py\\\", line 634, in run_until_complete\n    self.run_forever()\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/asyncio/base_events.py\\\", line 601, in run_forever\n    self._run_once()\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/asyncio/base_events.py\\\", line 1905, in _run_once\n    handle._run()\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/asyncio/events.py\\\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/server.py\\\", line 104, in serve_inner\n    model = get_model(model_id, revision, sharded, quantize)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/models/__init__.py\\\", line 112, in get_model\n    return llama_cls(model_id, revision, quantize=quantize)\n  File \\\"/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py\\\", line 39, in __init__\n    raise NotImplementedError(\\\"FlashLlama does not support quantization\\\")\nNotImplementedError: FlashLlama does not support quantization\n\""},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
```

Which means that we got past the point where the failure above happens @OlivierDehaene

**Comment by darth-veitcher** [comment] 2023-04-20 23:23
> ```shell
> The installed version of bitsandbytes was compiled without GPU support
> ```

Looks like a CUDA issue based on that error.

**Comment by sam-h-bean** [comment] 2023-04-21 02:37
@darth-veitcher I agree but when I check the pod it has a GPU allocated it from K8s and I am running bitsandbytes in a different pod on the same node just fine.

I put more details in this issue
https://github.com/huggingface/text-generation-inference/issues/197

**Comment by OlivierDehaene** [comment] 2023-04-21 06:52
Can you override the entrypoint with `/bin/bash` and args with `sleep 10000`, shell into the pod and:

1. run `nvidia-smi`
2. run `python`:

```python
import torch 

print(torch.cuda.is_available())

import bitsandbytes
```

**Comment by sam-h-bean** [comment] 2023-04-21 14:57
@OlivierDehaene as requested

```
# nvidia-smi 
Fri Apr 21 14:53:21 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   26C    P8    16W / 300W |      0MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
# python 
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
pri>>> print(torch.cuda.is_available())
False
>>> import bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Loading binary /opt/conda/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
```

So it seems that the CUDA version is N/A? I have never seen that one before.

On my other pod I ran the same command and see 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   32C    P0    58W / 300W |  19098MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
This pod is using a base image of `nvcr.io/nvidia/pytorch:22.12-py3` and an AMI of `ami-021248e8228eba010` which are both pretty basic...

**Comment by darth-veitcher** [comment] 2023-04-21 15:41
It will likely be the way that it’s resolving the linked CUDA libraries and it can’t find them. The `python -m bitsandbytes` usually contains some useful information but I imagine the use of Conda complicates things.

Would try running with the above command and getting the more verbose error messages it generates.

**Comment by darth-veitcher** [comment] 2023-04-21 16:50
Is it a windows host by any chance running this? Came across a similar edge case the other day where was running containers on WSL. Needed to add the following command. 

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib/wsl/lib
```

Your solution will likely need to be quite similar given the last segment of the error message. It can't find this environment variable.

**Comment by sam-h-bean** [comment] 2023-04-21 16:56
It is a Linux machine. I linked the AMI above. It's a standard Amazon Deep Learning machine image so I imagine this will be a common issue.

**Comment by OlivierDehaene** [comment] 2023-04-21 17:33
From what you reported it seems that you have a configuration issue with your node:

```python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
False <- torch does not seem to detect the GPU
```

Your driver seems really old. Maybe it is the root cause?

**Comment by darth-veitcher** [comment] 2023-04-21 19:11
I believe this is is the issue

```zsh
++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/opt/conda/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/opt/conda/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'
```

It's looking for `LD_LIBRARY_PATH` in the environment and can't find it. You usually get an output from the tool that says something along the lines of the below.

```zsh
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /home/user/miniconda3/envs/bits/lib/libcudart.so
CUDA SETUP: Loading binary /home/user/miniconda3/envs/bits/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
```

Solution with Conda which might work is something along the lines of this.

```zsh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/conda/lib/
```

I was fighting this issue the other day on a windows host and the above process resolved it for me followed by uninstalling `bitsandbytes` and reinstalling via `python -m pip install git+https://github.com/TimDettmers/bitsandbytes.git`.

The issue thread [bitsandbytes#112](https://github.com/TimDettmers/bitsandbytes/issues/112) was helpful.

**Comment by OlivierDehaene** [comment] 2023-04-21 19:34
I don't think it's related. The container works fine on our production environments with and without quantization. If the issue was with `LD_LIBRARY_PATH`, it simply would not work.
Also, in conda envs, `bitsandbytes` uses [the `CONDA_PREFIX` env var](https://github.com/search?q=repo%3ATimDettmers%2Fbitsandbytes%20CONDA_PREFIX&type=code) which is correctly set in [docker image](https://github.com/huggingface/text-generation-inference/blob/main/Dockerfile#L112).

**Comment by OlivierDehaene** [comment] 2023-04-21 19:40
I started a g5.12xlarge just to make sure.
Here is what I get:

```
(fast-neox) ubuntu@ip-172-31-42-134:~$ docker run --gpus all -it --entrypoint /bin/bash ghcr.io/huggingface/text-generation-inference:0.6.0
WARNING: Error loading config file: /home/ubuntu/.docker/config.json: open /home/ubuntu/.docker/config.json: permission denied
root@d47b97b21497:/usr/src# nvidia-smi
Fri Apr 21 19:37:01 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1B.0 Off |                    0 |
|  0%   27C    P8     9W / 300W |      0MiB / 23028MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A10G         On   | 00000000:00:1C.0 Off |                    0 |
|  0%   26C    P8     8W / 300W |      0MiB / 23028MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A10G         On   | 00000000:00:1D.0 Off |                    0 |
|  0%   26C    P8     9W / 300W |      0MiB / 23028MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   27C    P8    10W / 300W |      0MiB / 23028MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
root@d47b97b21497:/usr/src# python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> import bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
CUDA SETUP: CUDA runtime path found: /opt/conda/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /opt/conda/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
>>>
```

As you can see, torch.cuda.is_available() AND bitsandbytes work.

I'm almost 100% positive this is a driver issue. 
Either your driver is too old, or you are missing one of `datacenter-gpu-manager` or `cuda-drivers-fabricmanager`.

**Comment by sam-h-bean** [comment] 2023-04-21 20:43
@OlivierDehaene what AMI did you use?

**Comment by OlivierDehaene** [comment] 2023-04-24 12:22
amazon-eks-gpu-node-1.25-v20230217 (ami-02eaf06c708b0fad1) works for example.

**Closed** 2023-04-24 15:18 UTC
