### ISSUE TITLE
Unable to benchmark meta-llama/Llama-2-7b-chat-hf

### ISSUE THREAD

**Issue by abhinavkulkarni** [huggingface/text-generation-inference#760] opened 2023-08-02 17:29 UTC
### System Info

```
$ text-generation-launcher --env
2023-08-02T17:29:07.391215Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 7766fee9b15b6f600ee73db7f8bd72f7c62f335e
Docker label: N/A
nvidia-smi:
Wed Aug  2 17:29:07 2023       
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  NVIDIA GeForce RTX 3060         On | 00000000:01:00.0 Off |                  N/A |
   |  0%   33C    P8               13W / 170W|   7089MiB / 12288MiB |      0%      Default |
   |                                         |                      |                  N/A |
   +-----------------------------------------+----------------------+----------------------+
                                                                                            
   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   |    0   N/A  N/A   3037025      C   ...inav/miniconda3/envs/tgi/bin/python     7086MiB |
   +---------------------------------------------------------------------------------------+
   ```

### Reproduction & Expected behavior

I get the following error:

```
$ text-generation-benchmark --tokenizer-name meta-llama/Llama-2-7b-chat-hf
2023-08-02T17:28:10.107573Z  INFO text_generation_benchmark: benchmark/src/main.rs:126: Loading tokenizer
2023-08-02T17:28:10.107610Z  INFO text_generation_benchmark: benchmark/src/main.rs:135: Downloading tokenizer
2023-08-02T17:28:10.383069Z ERROR cached_path::cache: /home/abhinav/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cached-path-0.6.1/src/cache.rs:559: ETAG fetch for https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/tokenizer.json failed with fatal error    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Model \"meta-llama/Llama-2-7b-chat-hf\" on the Hub doesn't have a tokenizer"', benchmark/src/main.rs:147:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

Please note I am able to benchmark `bigscience/bloom-560m`.

**Comment by Narsil** [comment] 2023-08-03 08:33
Have you added `HUGGING_FACE_HUB_TOKEN` ? llama-v2 models are unfortunately gated, and therefore you need to use your personal token to access the tokenizer file.

Closing since it's likely to be the cause, please comment if that didn´t  solve it.

**Closed by Narsil** 2023-08-03 08:33 UTC

**Comment by abhinavkulkarni** [comment] 2023-08-04 02:37
Thanks, this solved the issue.
