### ISSUE TITLE
Qwen2-VL

### ISSUE THREAD

**Issue by jvhgit** [huggingface/text-generation-inference#2476] opened 2024-08-30 08:00 UTC
### Model description

[Qwen/Qwen2-VL-7B-Instruct](https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct
https://qwenlm.github.io/blog/qwen2-vl/
https://github.com/QwenLM/Qwen2-VL

**Comment by ErikKaum** [comment] 2024-08-30 15:01
Hi @jvhgit 👋 

Thanks for opening the issue.
Could you provide a bit more context, are you requesting for this model to be added?

**Comment by jvhgit** [comment] 2024-09-02 13:55
Hi, yes I am requesting this model (family) to be added. I think it is powerfull multimodal model based on my (basic) tests. 
Also, the license is apache 2.0 which makes it commercially permissive to run.

**Comment by ErikKaum** [comment] 2024-10-29 16:46
@jvhgit this is being worked on 🙌 can't promise a timeline but hopefully soon 🤞

**Comment by jvhgit** [comment] 2024-10-30 14:14
@ErikKaum thank you for your reply and good to hear this is being worked on. Keep up the good work!

**Comment by ErikKaum** [comment] 2024-11-26 10:19
Hi @maxjeblick 👋 

The model should work and be implemented. Could you open an issue such that the team can reproduce the bug?

**Comment by ErikKaum** [comment] 2024-11-26 10:20
Closing since it's supported in: https://github.com/huggingface/text-generation-inference/releases/tag/v2.4.1

**Closed by ErikKaum** 2024-11-26 10:20 UTC
Labels: new model

**Comment by maxjeblick** [comment] 2024-11-26 11:51
Thanks for the clarification, I created an issue [here.](https://github.com/huggingface/text-generation-inference/issues/2781)
