### ISSUE TITLE
Add support for AWQ quantized models

### ISSUE THREAD

**Issue by 0x1997** [huggingface/text-generation-inference#781] opened 2023-08-07 03:10 UTC
Compared to GPTQ, [AWQ](https://github.com/mit-han-lab/llm-awq) is more accurate and has much better inference performance.

Benchmark: https://github.com/lm-sys/FastChat/blob/main/docs/awq.md#benchmark

~Note: Multi-Query Attention is [not yet supported](https://github.com/mit-han-lab/llm-awq/issues/53#issuecomment-1659417305).~

**Comment by abhinavkulkarni** [comment] 2023-08-07 04:31
I have released a bunch of AWQ quantized models here: https://huggingface.co/abhinavkulkarni?sort_models=downloads#models

Instructions on how to run these with HuggingFace API are in the model cards.

**Comment by Narsil** [comment] 2023-08-07 10:27
Can anyone run benchmarks against TGI + exllama kernels ? 

Those are supposed to provide a similar speedup.

We don't want to support every quantization scheme in TGI, just the best possible subset:

- No quantization: best PPL
- bitsandbytes: Low vram - no quantization steps - works on every model
- GPTQ: Low VRAM - fasted inference (should be ~2x if I'm not mistaken) with exllama.

**Comment by abhinavkulkarni** [comment] 2023-08-07 13:44
@Narsil: Any kernel optimizations done for GPTQ should translate to AWQ since they both are based on similar zero-point quantization schemes - they simply differ on how those exact zero-point weights are found and admittedly AWQ is superior to GPTQ. 

So, someone needs to simply write a "_translator_" from AWQ to GPTQ state dicts and everything else should work as is.

**Comment by Narsil** [comment] 2023-08-07 16:34
> Besides, awq can be applied to LLMs other than Llama, where exllama cannot.

This statement is wrong `exllama` is just because the kernels where created here: https://github.com/turboderp/exllama it has nothing to do with llama. (In general current quantization techniques juste replace `Linear` with `QuantLinear` basically).

**Comment by edwardzjl** [comment] 2023-08-08 02:08
> > Besides, awq can be applied to LLMs other than Llama, where exllama cannot.
> 
> This statement is wrong `exllama` is just because the kernels where created here: https://github.com/turboderp/exllama it has nothing to do with llama. (In general current quantization techniques juste replace `Linear` with `QuantLinear` basically).

My apologies, I made an assumption about exllama based solely on its name. I mistakenly thought it was specifically for Llama models. :sweat_smile:

**Comment by Narsil** [comment] 2023-08-08 07:26
No worries.

**Comment by casperbh96** [comment] 2023-08-08 12:55
My own benchmark from AWQ is 134 tokens/s (7.46 ms/token) on a 4090+i9-13900k for MPT 7B models.

As Narsil mentions, quantization methods mostly replace Linear with QuantLinear layers. AWQ does this with their optimized [GEMM kernel](https://github.com/mit-han-lab/llm-awq/blob/main/tinychat/modules/fused_mlp.py#L11). Additionally, AWQ Tinychat runs the following optimizations for LLaMa models specifically:

- Rotary embedding neox [attention kernel](https://github.com/mit-han-lab/llm-awq/blob/main/tinychat/modules/fused_attn.py#L11) from vLLM
- [RMSNorm kernel](https://github.com/mit-han-lab/llm-awq/blob/main/tinychat/modules/fused_norm.py#L6C1-L6C1) from FasterTransformer

LLaMa models are 100+ tokens/s.

### Why AWQ is faster than GPTQ

AWQ **is** faster than GPTQ. It is **not** faster than exllama because exllama runs a lot of kernel optimizations on top to make it faster. But the problem is that exllama is written explicitly to optimize LLaMa models, so the full performance boost will not be seen in other models.

From the [AWQ paper](https://arxiv.org/pdf/2306.00978.pdf):

> Different weight channels have different importance; updating the salient channels to compensate for the non-salient ones will likely destroy the performance. Reordering prevents it by quantizing important channels first. However, it will lead to bad hardware efficiency due to irregular memory access (Figure 2), while our scaling method does not suffer from the issue.

![image](https://github.com/huggingface/text-generation-inference/assets/27340033/103c75df-a728-4cda-a044-5f8fc417d707)

**Comment by abhinavkulkarni** [comment] 2023-08-11 17:41
Hi,

I have added rudimentary support for AWQ models at https://github.com/abhinavkulkarni/text-generation-inference/tree/abhinavkulkarni/add-awq-support

You can view the side-by-side changes [here](https://github.com/huggingface/text-generation-inference/compare/main...abhinavkulkarni:text-generation-inference:abhinavkulkarni/add-awq-support?expand=1).

This requires installing AWQ library and CUDA kernels for 4-bit matrix multiplication:

```bash
git clone https://github.com/mit-han-lab/llm-awq \
&& cd llm-awq \
&& git checkout ce4a6bb1c238c014a06672cb74f6865573494d66 \
&& pip install -e . \
&& cd awq/kernels \
&& python setup.py install
```

After that

```
git clone https://github.com/abhinavkulkarni/text-generation-inference.git \
&& git checkout abhinavkulkarni/add-awq-support
```

I was able to run the server as follows:

`SAFETENSORS_FAST_GPU=1 python -m torch.distributed.run --nproc_per_node=1 text_generation_server/cli.py serve abhinavkulkarni/meta-llama-Llama-2-7b-chat-hf-w4-g128-awq --quantize awq`

and the router as follows:

`cd router && cargo run -- --port 8080 --tokenizer-name abhinavkulkarni/meta-llama-Llama-2-7b-chat-hf-w4-g128-awq --max-input-length 4000 --max-total-tokens 4096`

This change of course borrows from AWQ library and for zero-point quantization, I use the `WQLinear` layer which is very similar to `QuantLinear` layer in TGI. For now, I have hardcoded the values of `bits` to `4` and `groupsize` to `128`, but should be possible to read them off `quantize.json`. None of my models have `quantize.json` yet, but update the repos with one.

I don't think this change is comprehensive and I would welcome any pull requests.

Thanks!

CC: @casperbh96, @Narsil

**Comment by abhinavkulkarni** [comment] 2023-08-12 03:05
I benchmarked Llama 2 AWQ vs GPTQ with FlashAttention v1 and vLLM. Note, I do not have exllama installed. Following are the results:

AWQ model_id: `abhinavkulkarni/meta-llama-Llama-2-7b-chat-hf-w4-g128-awq`
GPTQ model_id: `TheBloke/Llama-2-7b-Chat-GPTQ`

GPTQ benchmarks:

```
| Parameter          | Value                         |
|--------------------|-------------------------------|
| Model              | TheBloke/Llama-2-7b-Chat-GPTQ |
| Sequence Length    | 10                            |
| Decode Length      | 8                             |
| N Runs             | 10                            |
| Warmups            | 1                             |
| Temperature        | None                          |
| Top K              | None                          |
| Top P              | None                          |
| Typical P          | None                          |
| Repetition Penalty | None                          |
| Watermark          | false                         |
| Do Sample          | false                         |


| Step           | Batch Size | Average   | Lowest    | Highest   | p50       | p90       | p99       |
|----------------|------------|-----------|-----------|-----------|-----------|-----------|-----------|
| Prefill        | 1          | 41.23 ms  | 41.16 ms  | 41.39 ms  | 41.22 ms  | 41.39 ms  | 41.39 ms  |
|                | 2          | 47.80 ms  | 47.72 ms  | 47.88 ms  | 47.81 ms  | 47.88 ms  | 47.88 ms  |
|                | 4          | 57.94 ms  | 57.83 ms  | 58.02 ms  | 57.95 ms  | 58.02 ms  | 58.02 ms  |
|                | 8          | 108.53 ms | 108.39 ms | 108.81 ms | 108.56 ms | 108.81 ms | 108.81 ms |
|                | 16         | 153.65 ms | 153.22 ms | 156.46 ms | 153.35 ms | 156.46 ms | 156.46 ms |
|                | 32         | 251.93 ms | 251.04 ms | 252.23 ms | 252.05 ms | 252.23 ms | 252.23 ms |
| Decode (token) | 1          | 40.33 ms  | 40.27 ms  | 40.45 ms  | 40.32 ms  | 40.32 ms  | 40.32 ms  |
|                | 2          | 40.83 ms  | 40.80 ms  | 40.90 ms  | 40.84 ms  | 40.82 ms  | 40.82 ms  |
|                | 4          | 41.07 ms  | 40.81 ms  | 41.15 ms  | 41.10 ms  | 40.81 ms  | 40.81 ms  |
|                | 8          | 41.28 ms  | 41.25 ms  | 41.34 ms  | 41.28 ms  | 41.29 ms  | 41.29 ms  |
|                | 16         | 48.03 ms  | 47.92 ms  | 48.22 ms  | 48.04 ms  | 47.95 ms  | 47.95 ms  |
|                | 32         | 59.45 ms  | 59.35 ms  | 59.65 ms  | 59.42 ms  | 59.65 ms  | 59.65 ms  |
| Decode (total) | 1          | 282.34 ms | 281.92 ms | 283.14 ms | 282.27 ms | 282.25 ms | 282.25 ms |
|                | 2          | 285.83 ms | 285.61 ms | 286.33 ms | 285.86 ms | 285.76 ms | 285.76 ms |
|                | 4          | 287.48 ms | 285.70 ms | 288.08 ms | 287.68 ms | 285.70 ms | 285.70 ms |
|                | 8          | 288.99 ms | 288.73 ms | 289.37 ms | 288.97 ms | 289.00 ms | 289.00 ms |
|                | 16         | 336.21 ms | 335.45 ms | 337.57 ms | 336.28 ms | 335.63 ms | 335.63 ms |
|                | 32         | 416.15 ms | 415.43 ms | 417.57 ms | 415.96 ms | 417.57 ms | 417.57 ms |


| Step    | Batch Size | Average            | Lowest             | Highest            |
|---------|------------|--------------------|--------------------|--------------------|
| Prefill | 1          | 24.25 tokens/secs  | 24.16 tokens/secs  | 24.30 tokens/secs  |
|         | 2          | 41.84 tokens/secs  | 41.77 tokens/secs  | 41.92 tokens/secs  |
|         | 4          | 69.04 tokens/secs  | 68.94 tokens/secs  | 69.17 tokens/secs  |
|         | 8          | 73.71 tokens/secs  | 73.52 tokens/secs  | 73.81 tokens/secs  |
|         | 16         | 104.14 tokens/secs | 102.26 tokens/secs | 104.43 tokens/secs |
|         | 32         | 127.02 tokens/secs | 126.87 tokens/secs | 127.47 tokens/secs |
| Decode  | 1          | 24.79 tokens/secs  | 24.72 tokens/secs  | 24.83 tokens/secs  |
|         | 2          | 48.98 tokens/secs  | 48.89 tokens/secs  | 49.02 tokens/secs  |
|         | 4          | 97.40 tokens/secs  | 97.20 tokens/secs  | 98.00 tokens/secs  |
|         | 8          | 193.78 tokens/secs | 193.53 tokens/secs | 193.95 tokens/secs |
|         | 16         | 333.13 tokens/secs | 331.78 tokens/secs | 333.88 tokens/secs |
|         | 32         | 538.27 tokens/secs | 536.43 tokens/secs | 539.21 tokens/secs |
```

AWQ benchmarks:

```
| Parameter          | Value                                                     |
|--------------------|-----------------------------------------------------------|
| Model              | abhinavkulkarni/meta-llama-Llama-2-7b-chat-hf-w4-g128-awq |
| Sequence Length    | 10                                                        |
| Decode Length      | 8                                                         |
| N Runs             | 10                                                        |
| Warmups            | 1                                                         |
| Temperature        | None                                                      |
| Top K              | None                                                      |
| Top P              | None                                                      |
| Typical P          | None                                                      |
| Repetition Penalty | None                                                      |
| Watermark          | false                                                     |
| Do Sample          | false                                                     |

| Step           | Batch Size | Average   | Lowest    | Highest   | p50       | p90       | p99       |
|----------------|------------|-----------|-----------|-----------|-----------|-----------|-----------|
| Prefill        | 1          | 18.84 ms  | 18.70 ms  | 19.25 ms  | 18.75 ms  | 19.25 ms  | 19.25 ms  |
|                | 2          | 31.18 ms  | 31.05 ms  | 31.37 ms  | 31.19 ms  | 31.37 ms  | 31.37 ms  |
|                | 4          | 46.88 ms  | 46.63 ms  | 47.25 ms  | 46.90 ms  | 47.25 ms  | 47.25 ms  |
|                | 8          | 78.74 ms  | 78.44 ms  | 79.09 ms  | 78.81 ms  | 79.09 ms  | 79.09 ms  |
|                | 16         | 154.59 ms | 154.09 ms | 154.96 ms | 154.75 ms | 154.96 ms | 154.96 ms |
|                | 32         | 308.17 ms | 307.61 ms | 308.79 ms | 308.21 ms | 308.79 ms | 308.79 ms |
| Decode (token) | 1          | 16.21 ms  | 16.11 ms  | 16.69 ms  | 16.14 ms  | 16.69 ms  | 16.69 ms  |
|                | 2          | 16.62 ms  | 16.54 ms  | 16.80 ms  | 16.63 ms  | 16.80 ms  | 16.80 ms  |
|                | 4          | 17.28 ms  | 17.18 ms  | 17.42 ms  | 17.31 ms  | 17.42 ms  | 17.42 ms  |
|                | 8          | 18.56 ms  | 18.52 ms  | 18.61 ms  | 18.56 ms  | 18.61 ms  | 18.61 ms  |
|                | 16         | 22.51 ms  | 21.77 ms  | 28.57 ms  | 21.86 ms  | 28.57 ms  | 28.57 ms  |
|                | 32         | 37.61 ms  | 37.58 ms  | 37.67 ms  | 37.61 ms  | 37.67 ms  | 37.67 ms  |
| Decode (total) | 1          | 113.47 ms | 112.78 ms | 116.80 ms | 113.01 ms | 116.80 ms | 116.80 ms |
|                | 2          | 116.37 ms | 115.81 ms | 117.60 ms | 116.43 ms | 117.60 ms | 117.60 ms |
|                | 4          | 120.99 ms | 120.27 ms | 121.94 ms | 121.15 ms | 121.94 ms | 121.94 ms |
|                | 8          | 129.91 ms | 129.65 ms | 130.25 ms | 129.91 ms | 130.25 ms | 130.25 ms |
|                | 16         | 157.60 ms | 152.36 ms | 199.98 ms | 153.04 ms | 199.98 ms | 199.98 ms |
|                | 32         | 263.28 ms | 263.03 ms | 263.70 ms | 263.27 ms | 263.70 ms | 263.70 ms |

| Step    | Batch Size | Average            | Lowest             | Highest            |
|---------|------------|--------------------|--------------------|--------------------|
| Prefill | 1          | 53.09 tokens/secs  | 51.94 tokens/secs  | 53.49 tokens/secs  |
|         | 2          | 64.14 tokens/secs  | 63.75 tokens/secs  | 64.41 tokens/secs  |
|         | 4          | 85.32 tokens/secs  | 84.66 tokens/secs  | 85.78 tokens/secs  |
|         | 8          | 101.60 tokens/secs | 101.16 tokens/secs | 101.99 tokens/secs |
|         | 16         | 103.50 tokens/secs | 103.25 tokens/secs | 103.83 tokens/secs |
|         | 32         | 103.84 tokens/secs | 103.63 tokens/secs | 104.03 tokens/secs |
| Decode  | 1          | 61.70 tokens/secs  | 59.93 tokens/secs  | 62.07 tokens/secs  |
|         | 2          | 120.31 tokens/secs | 119.05 tokens/secs | 120.89 tokens/secs |
|         | 4          | 231.43 tokens/secs | 229.62 tokens/secs | 232.81 tokens/secs |
|         | 8          | 431.08 tokens/secs | 429.94 tokens/secs | 431.94 tokens/secs |
|         | 16         | 715.32 tokens/secs | 560.06 tokens/secs | 735.11 tokens/secs |
|         | 32         | 850.79 tokens/secs | 849.43 tokens/secs | 851.62 tokens/secs |
```

Thanks!

**Comment by Narsil** [comment] 2023-08-12 07:24
@abhinavkulkarni Can you try with exllama please? 

It looks very promising !

**Comment by abhinavkulkarni** [comment] 2023-08-12 17:59
Hey @Narsil,

I am unable to install Exllama GPTQ kernels even when I run `BUILD_EXTENSIONS=True make install`.

Do I need to install them separately?

**Comment by bloodsucker99** [comment] 2023-08-15 17:28
I also cannot run exllama kernel. I never get that log whenever i run any gptq model..

**Comment by 0x1997** [comment] 2023-08-21 10:19
Thanks for @abhinavkulkarni‘s code, I did some simple evaluation. The output quality of AWQ model is a little bit worse than GPTQ. But the 60% speedup at inference is quite nice.

My branch is at https://github.com/0x1997/text-generation-inference/tree/awq.

Currently multi GPU support is broken, the model generates garbled outputs like this. Do you have any idea how to fix this? @abhinavkulkarni 
```
re,:,\\\\.,,,,,,,,,,,,,,,,,,,,,,, a rad, k,,,,,,,,,,,,,,,,,,,e\\\\ the the they, I have,,,,,,,,,, the\\\\ and, I\\\\,,,,,,,,,,,.,\\\\anded the the\\\\\\\\\\\\,,,. the thesers,\\\\\\\\ and, ap\\\\\\\\\\\\\\\\ the, a\\\\ and.\\\\\\\\\\\\\\\\.,,,,,,,,,,,, a I,,,:,\\\\, avision, aon,,,,,,,,,,,, in a a the the ,,,,,,,,,,,, a, a a the the ,,,,,,- the the the the\\\\ made\\,, the k,,,,,,.,,,,,a a,,,,,,, the, a a,her it,,,,,,, a a,,,,,, the it,,, theo and., you., the,
```

**Comment by sjzhou4** [comment] 2023-08-31 02:05
@abhinavkulkarni https://github.com/huggingface/text-generation-inference/issues/948
This issue is tried by your awq method, can you help to solve this problem? Thank you.

**Comment by MichaelHauser0971** [comment] 2023-09-07 11:20
> Thanks for @abhinavkulkarni‘s code, I did some simple evaluation. The output quality of AWQ model is a little bit worse than GPTQ. But the 60% speedup at inference is quite nice.
> 
> My branch is at https://github.com/0x1997/text-generation-inference/tree/awq.
> 
> Currently multi GPU support is broken, the model generates garbled outputs like this. Do you have any idea how to fix this? @abhinavkulkarni
> 
> ```
> re,:,\\\\.,,,,,,,,,,,,,,,,,,,,,,, a rad, k,,,,,,,,,,,,,,,,,,,e\\\\ the the they, I have,,,,,,,,,, the\\\\ and, I\\\\,,,,,,,,,,,.,\\\\anded the the\\\\\\\\\\\\,,,. the thesers,\\\\\\\\ and, ap\\\\\\\\\\\\\\\\ the, a\\\\ and.\\\\\\\\\\\\\\\\.,,,,,,,,,,,, a I,,,:,\\\\, avision, aon,,,,,,,,,,,, in a a the the ,,,,,,,,,,,, a, a a the the ,,,,,,- the the the the\\\\ made\\,, the k,,,,,,.,,,,,a a,,,,,,, the, a a,her it,,,,,,, a a,,,,,, the it,,, theo and., you., the,
> ```

Have you solved this problem? I also encountered the same problem.

**Comment by abhinavkulkarni** [comment] 2023-09-12 02:25
@0x1997, @MichaelHauser0971: I haven't tested the multi-GPU AWQ setup, but it should be possible. Just focussing on single-GPU setup for now.

@Narsil: Any interest in adding AWQ support? In general, It is faster and more accurate than GPTQ.

You can look at the diff [here](https://github.com/huggingface/text-generation-inference/compare/main...abhinavkulkarni:text-generation-inference:abhinavkulkarni/add-awq-support?expand=1). Happy to raise a PR if there's enough interest to add AWQ support. You can also try my branch with any other models released [here](https://huggingface.co/abhinavkulkarni?sort_models=downloads#models). The model repo simply contains the state dict containing zero-point quantized weights and `quantize_config.json`.

Can you please take a look at my replies at https://github.com/huggingface/text-generation-inference/issues/781#issuecomment-1675646805 and https://github.com/huggingface/text-generation-inference/issues/781#issuecomment-1676032586?

Please note that AWQ has fused kernels for Llama, the benchmarks in the above replies were obtained with default kernels. Fused kernels should improve the performance further.

**Comment by dingjingzhen** [comment] 2023-09-13 10:02
> Can anyone run benchmarks against TGI + exllama kernels ?
> 
> Those are supposed to provide a similar speedup.
> 
> We don't want to support every quantization scheme in TGI, just the best possible subset:
> 
> * No quantization: best PPL
> * bitsandbytes: Low vram - no quantization steps - works on every model
> * GPTQ: Low VRAM - fasted inference (should be ~2x if I'm not mistaken) with exllama.
This works very good, I measured almost no ppl loss, but the performance is faster than gptq
https://github.com/huggingface/text-generation-inference/pull/1018

**Comment by dingjingzhen** [comment] 2023-09-13 10:05
Try this solution of ours, the best ppl with faster performance than gptq
https://github.com/huggingface/text-generation-inference/pull/1018
Below is our test on 3090. environment: torch=2.01, cuda=11.8, nvidia driver: 525.78.01
prompt=1024, max_new_tokens=50
![image](https://github.com/huggingface/text-generation-inference/assets/21244263/4bef52b1-8174-4a6e-90b3-147a2d9c90af)

**Comment by abhinavkulkarni** [comment] 2023-09-13 11:27
@Narsil: I have opened a PR https://github.com/huggingface/text-generation-inference/pull/1019 for adding AWQ support for `FlashLlama` models. Please take a look. Please refer to earlier replies from me for benchmarking results against GPTQ.

@MichaelHauser0971, @sjzhou4, @0x1997, @casper-hansen: I have not yet tested multi-GPU setup, lets first try to get approval for single-GPU PR.

**Comment by casper-hansen** [comment] 2023-09-13 14:25
@ryanshrott vLLM support for AWQ is close to being merged, check their branch out:
https://github.com/vllm-project/vllm/tree/add_awq_quant_support

**Comment by abhinavkulkarni** [comment] 2023-09-13 14:35
@ryanshrott: Please check the PR I have raised. It runs a Llama 2 model with FlashAttention v2 and vLLM.

**Comment by TheBloke** [comment] 2023-09-22 17:11
Great to hear! I've uploaded plenty of models to be used with it :)
![image](https://github.com/huggingface/text-generation-inference/assets/784313/089bbc84-5870-46d0-b8d3-bdf69ce87dbf)

My READMEs linked to this PR and mentioned support was coming 'soon'.  Once this is merged I can update them all to include TGI details.

**Comment by ryanshrott** [comment] 2023-09-22 17:17
Will this PR have comparable speeds to regular non-quantized models? 

I currently find AW! quantization with VLLM to run very slow.

**Comment by casper-hansen** [comment] 2023-09-22 17:24
INT4 throughput will not be higher than FP16 at very high data parallelism. For that, you must use INT8 or FP16.

**Comment by ryanshrott** [comment] 2023-09-22 18:03
@casper-hansen I'm not quite following all your technical notes. Are you saying that 4-bit awq will be fast or not?

**Comment by casper-hansen** [comment] 2023-09-22 19:08
Yes, it can be much faster. But like I just explained, there are cases where it will not be faster. It depends on your use-case.

**Comment by RonanKMcGovern** [comment] 2023-09-23 15:10
Will this approach default to using GEMM? or is there a parameters where one can configure GEMV or fp16?

I may be missing something in the code updates, I just didn't find any reference to GEMM.

Also, great work on this.

**Comment by casper-hansen** [comment] 2023-09-23 15:37
GEMV is only faster at batch size 1 with a small context (20% faster). For deployment purposes with many concurrent requests, GEMM will overall be much faster as it scales better. @RonanKMcGovern

**Closed** 2023-09-25 13:31 UTC

**Comment by RonanKMcGovern** [comment] 2023-09-25 14:55
I pulled this [image](https://github.com/huggingface/text-generation-inference/pkgs/container/text-generation-inference/131198235?tag=sha-c5de7cd) and it's recognising awq.

1.0.3 from the readme won't work for awq though. Might be worth putting a note there in the readme if not ready for a release?

Also, after trying the following flags on the latest image:
```
--model-id TheBloke/Llama-2-70B-chat-AWQ --trust-remote-code --port 8080 --max-input-length 2048 --max-total-tokens 4096 --max-batch-prefill-tokens 4096 --quantize awq
```
I'm hitting:
```
2023-09-25T07:54:05.251889450-07:00     return callback(**use_params)  # type: ignore
2023-09-25T07:54:05.251891440-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 82, in serve
2023-09-25T07:54:05.251893660-07:00     server.serve(
2023-09-25T07:54:05.251895730-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
2023-09-25T07:54:05.251898130-07:00     asyncio.run(
2023-09-25T07:54:05.251900180-07:00   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-09-25T07:54:05.251902330-07:00     return loop.run_until_complete(main)
2023-09-25T07:54:05.251905440-07:00   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
2023-09-25T07:54:05.251907560-07:00     self.run_forever()
2023-09-25T07:54:05.251909610-07:00   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
2023-09-25T07:54:05.251911670-07:00     self._run_once()
2023-09-25T07:54:05.251913740-07:00   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
2023-09-25T07:54:05.251915790-07:00     handle._run()
2023-09-25T07:54:05.251917850-07:00   File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
2023-09-25T07:54:05.251920010-07:00     self._context.run(self._callback, *self._args)
2023-09-25T07:54:05.251924120-07:00 > File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
2023-09-25T07:54:05.251926260-07:00     model = get_model(
2023-09-25T07:54:05.251928480-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 187, in get_model
2023-09-25T07:54:05.251930600-07:00     return FlashLlama(
2023-09-25T07:54:05.251932640-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 68, in __init__
2023-09-25T07:54:05.251934730-07:00     model = FlashLlamaForCausalLM(config, weights)
2023-09-25T07:54:05.251936780-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 474, in __init__
2023-09-25T07:54:05.251939230-07:00     self.model = FlashLlamaModel(config, weights)
2023-09-25T07:54:05.251941310-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 412, in __init__
2023-09-25T07:54:05.251943390-07:00     [
2023-09-25T07:54:05.251945510-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 413, in <listcomp>
2023-09-25T07:54:05.251947630-07:00     FlashLlamaLayer(
2023-09-25T07:54:05.251949740-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 349, in __init__
2023-09-25T07:54:05.251951740-07:00     self.self_attn = FlashLlamaAttention(
2023-09-25T07:54:05.251953700-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 229, in __init__
2023-09-25T07:54:05.251955840-07:00     self.query_key_value = load_attention(config, prefix, weights)
2023-09-25T07:54:05.251957850-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 154, in load_attention
2023-09-25T07:54:05.251959930-07:00     return _load_gqa(config, prefix, weights)
2023-09-25T07:54:05.251962000-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 183, in _load_gqa
2023-09-25T07:54:05.251966830-07:00     weight = weight.to(dtype=weights.dtype).to(device=weights.device)
2023-09-25T07:54:05.251968970-07:00 AttributeError: 'tuple' object has no attribute 'to'
```

**Comment by RonanKMcGovern** [comment] 2023-09-25 15:31
Thanks @abhinavkulkarni !

- Yes, I have no issues on the 7B model on an A6000.
- I have now tried the 70B model on an A6000 (error as per above) and also on a A100. The A100 with 80 GB is giving the same error.

**Comment by naticio** [comment] 2023-10-14 00:36
so.....can we run any awq model using TGI or just some of them (as of now)

trying to launch text-generation-launcher --model-id TheBloke/Wizard-Vicuna-30B-Uncensored-AWQ

but doesn;t work

RuntimeError: weight model.layers.0.self_attn.q_proj.weight does not exist
rank=0
2023-10-14T00:15:44.698002Z ERROR text_generation_launcher: Shard 0 failed to start
2023-10-14T00:15:44.698035Z INFO text_generation_launcher: Shutting down shards

**Comment by abhinavkulkarni** [comment] 2023-10-14 03:07
@naticio: Currently only `FlashLlama` models are supported for AWQ quantization. So, the underlying model has to be a Llama 1 or 2 architecture.
