### ISSUE TITLE
Contrastive Search

### ISSUE THREAD

**Issue by paulcx** [huggingface/text-generation-inference#320] opened 2023-05-12 21:50 UTC
### Feature request

I'm wondering if the new Contrastive Search would be supported soon?

### Motivation

https://huggingface.co/blog/introducing-csearch

### Your contribution

n/a

**Comment by OlivierDehaene** [comment] 2023-05-13 08:42
Duplicate of #113

**Closed by OlivierDehaene** 2023-05-13 08:42 UTC
