### ISSUE TITLE
Running Multiple Models on Same GPU

### ISSUE THREAD

**Issue by csnelsonchu** [huggingface/text-generation-inference#323] opened 2023-05-14 11:54 UTC
### Feature request

NVIDIA Triton can running multiple models under the same GPU.
I didn't see this as an option for this project.
Is that possible as of today or this needs to be a new feature?

### Motivation

GPU are expensive, especially when running on large model that needs the A40 and A100.
It will be great if I can move more models than the number of GPUs.

### Your contribution

Sure, I can contribute if development is needed.

**Comment by OlivierDehaene** [comment] 2023-05-14 12:45
Duplicate of #312

**Closed by OlivierDehaene** 2023-05-14 12:45 UTC
