### ISSUE TITLE
The performance of TGI is not good as FT because of nccl-communication when using 8gpus

### ISSUE THREAD

**Issue by jameswu2014** [huggingface/text-generation-inference#863] opened 2023-08-17 07:17 UTC
### System Info

I recently conducted performance analysis on TGI and FT. I used 8 GPUs for testing and observed that, during the decoder phase, TGI's time consumption is primarily attributed to communication, accounting for approximately 50% of the total time, whereas FT's communication overhead during the decoder phase is around 20%. The communication pattern of TGI experiences significant fluctuations due to the presence of 8 processes, resulting in waiting times being influenced by the slowest process. On the other hand, FT exhibits relatively stable behavior. I would like to inquire about potential solutions to address this issue.

FT-profiling：
![fgjIkflmw1](https://github.com/huggingface/text-generation-inference/assets/8462999/b16e491f-7807-4d76-9283-5f8d61ae1e1b)

TGI-profiling：
![EDV7SS0kfv](https://github.com/huggingface/text-generation-inference/assets/8462999/01e1a85d-a1f0-4095-bf67-28db402e0ed3)

As you can see, FT nccl-all-reduce is aligned very well, However, For tgi, there is always one  process is slower than others,and cause other process waiting for.

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

nsys profile ft/tgi

### Expected behavior

tgi timing like ft.

**Comment by Narsil** [comment] 2023-08-17 07:24
I have no idea.

If I was able to reproduce I would maybe be able to look into it. 
Many things might be at play here.

**Comment by jameswu2014** [comment] 2023-08-17 10:08
> I have no idea.
> 
> If I was able to reproduce I would maybe be able to look into it. Many things might be at play here.

Did you compared the twos before?

**Comment by Narsil** [comment] 2023-08-17 14:18
We did. I don't  have the specifics in mind. 
NCCL desync can happen, but it's really hard to make consistent.

Lots of things are happening here, cuda version. hardware, model under the hood, TGI version, the actual set of features being used.

NCCL being "big" in profiling, doesn't necessarily  mean it is the issue. NCCL is blocking, if some GPUs are slower than others for whatever reason, then ofc they will force every other GPU to wait on the other.

I've had similar issue in `candle` when using multithreaded multi GPU control. Turns out there's a global mutex in cuda driver, making multithreaded control pretty underwhelming (and the consequence is what you're seeing here basically). The mutex is the issue, not NCCL, yet becuase of the mutex, we cannot send the kernels fast enough on each GPU, and NCCL looks likeit's taking too much time.

**Comment by jameswu2014** [comment] 2023-08-17 15:37
> 

Yes, My issue is the same as yours, kernels is send too slowly so that slower GPU will be waited.the slower gpu is different each  decode a token time.

**Comment by jameswu2014** [comment] 2023-08-17 15:39
> > 
> 
> Yes, My issue is the same as yours, kernels is send too slowly so that slower GPU will be waited.the slower gpu is different each decode a token time.

I feel like it is a TGI's issue, it is not relevant with specific models or something others.

**Comment by Narsil** [comment] 2023-08-17 15:41
If you can provide the necessary information so that I could reproduce I could take a look.

**Comment by jameswu2014** [comment] 2023-08-18 02:21
> 

model: llama 65B
docker: tgi0.9.4
GPU: 8x A800(80GB) or 8x 3090 or 8x A100(80GB), we all tried.
cmd:
     server:  nsys launch --session-new=abc text-generation-launcher --model-id xxxx  --num-shard 8 --max-total-tokens 6144 --max-input-length 4096 --max-concurrent-requests 2048 --max-batch-prefill-tokens 58000 --max-best-of 1 --dtype bfloat16
     
      client:
            nsys start --session=abc
            YOUR REQUEST
            nsys stop --session=abc

**Comment by jameswu2014** [comment] 2023-08-18 05:49
I found FT's kernel launch interval time is about 4us, whereas TGI's is about 37us. Maybe this is the root cause.

**Comment by Narsil** [comment] 2023-08-18 10:03
> I found FT's kernel launch interval time is about 4us, whereas TGI's is about 37us. Maybe this is the root cause. So， python kernel launch interval time is larger than c++?

Very likely, It's not all that surprising we're writing: https://github.com/huggingface/candle/

**Comment by OlivierDehaene** [comment] 2024-01-10 15:42
#1428 will help a lot for this.

**Comment by Narsil** [comment] 2024-02-13 12:16
Closing since with the addition of cuda graphs (still experimental since some edge cases/GPU it might fail). This should be gone.

**Closed by Narsil** 2024-02-13 12:16 UTC
