### ISSUE TITLE
GLM Model

### ISSUE THREAD

**Issue by wqh17101** [huggingface/text-generation-inference#572] opened 2023-07-10 04:27 UTC
### Model description

https://github.com/THUDM/ChatGLM2-6B
https://huggingface.co/THUDM/chatglm2-6b/tree/main

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by OlivierDehaene** [comment] 2023-07-10 09:21
Duplicate of #524

**Closed by OlivierDehaene** 2023-07-10 09:21 UTC

**Comment by zhanzushun** [comment] 2024-05-22 09:24
ChatGLM3 IS a very popular model. Hope add to supported list. Thanks
