### ISSUE TITLE
max-batch-total-tokens deprecated

### ISSUE THREAD

**Issue by meitalbensinai** [huggingface/text-generation-inference#1245] opened 2023-11-08 11:15 UTC
### System Info

In the past, I could run the tgi server with `--max-batch-total-tokens`.
You deprecated this ability for  Flash Attention models.
I want the server to use only a fraction of my GPU memory, and I want to be able to decide this value.
Why don't you take the minimum value between the provided value and the max_tokens calculated automatically?
In the current solution, it always uses the maximum memory amount it can.

```
`--max-batch-total-tokens` is deprecated for Flash Attention models.
WARN text_generation_router: router/src/main.rs:232: Inferred max batch total tokens: 3440688
``` 

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

always, the values change based on the GPU type and memory availability 

### Expected behavior

I think it should be possible to decide it from outside

**Comment by Rogerwyf** [comment] 2023-11-08 18:31
> I want the server to use only a fraction of my GPU memory, and I want to be able to decide this value.

You can use `--cuda-memory-fraction` to set how much GPU memory to be visible to the TGI container.

**Comment by meitalbensinai** [comment] 2023-11-08 19:24
It's a start but it still problematic
I want to run 2 services in the same machine and I don't want this value to be dependent on who is going up first

```free_memory = max(
            0, total_free_memory - (1 - MEMORY_FRACTION) * total_gpu_memory
        )```

It seems that this value would get different values based on the initialization order while I want it to be fixed

**Comment by thomas-schillaci** [comment] 2023-11-21 13:44
Hello, I'm bumping this issue as I also find that cuda_memory_fraction is dependent on the amount of available memory.
I'm loading a bofenghuang/vigostral-7b-chat with cuda_memory_fraction=0.29 without issue on a non-used 80Gb GPU, but running the same startup command with the same GPU, but with 50Gb of non-used memory, fails.

**Comment by Narsil** [comment] 2023-12-05 10:57
It's not actually, it's more that there are a lot of fixed size memory costs which are hindering those ratio to work perfectly.

Try running less close to those boundaries, with ~40GB and 0.29 or reduce the ratio, for instance.

The operation is actually independant of free RAM.
```
(1 - MEMORY_FRACTION) * total_gpu_memory
```

**Comment by meitalbensinai** [comment] 2023-12-05 11:15
https://github.com/huggingface/text-generation-inference/blob/25b5f8194186f651111dac8a0bfd3d2a1d244c40/server/text_generation_server/models/flash_causal_lm.py#L690

But this is the operation.

**Comment by thomas-schillaci** [comment] 2024-01-08 13:34
@Narsil any update on this? Following @meitalbensinai 's comment, I also get issues when loading models on GPUs with allocated memory

**Comment by Narsil** [comment] 2024-01-10 18:03
Wait, you cannot load 2 models with each having `--cuda-memory-fraction 0.5`, is that correct ? If so then yes, I'd classify that as a bug.

**Comment by thomas-schillaci** [comment] 2024-01-11 07:31
My bug is different, if I load a model with --cuda-memory-fraction 0.29 on a GPU completely free, I don't get any issue.
If the GPU has at least 3% of used VRAM (so 97% free), it doesn't load (OOM)

**Comment by Narsil** [comment] 2024-01-11 11:36
I cannot reproduce unfortunately. Are you sure it's not because you simply don't allow enough VRAM with 0.29 ?

**Comment by thomas-schillaci** [comment] 2024-01-12 15:14
I think this problem might only affect models that don't support flash attention, for example bofenghuang/vigostral-7b-chat
To reproduce on an A100:

Working scenario:

1. On an empty GPU, run `docker run --shm-size 1g -p 8080:80 -v /data/huggingface/hub:/data -v /lib64/libcuda.so:/lib64/libcuda.so ghcr.io/huggingface/text-generation-inference:1.3.3 --model-id /data/models--bofenghuang--vigostral-7b-chat/snapshots/969fbfc7a91f53c8562a2c48a3c24dd3745d5a97 --num-shard 1 --trust-remote-code --max-input-length 8192 --max-total-tokens 16384 --max-batch-prefill-tokens 16384 --max-concurrent-requests 256 --cuda-memory-fraction 0.29`
2. The container sets up correctly, and is able to answer requests

Breaking scenario:

1. Charge a small model on the GPU, for example `docker run --shm-size 1g -p 8081:80 -v /data/huggingface/hub:/data -v /lib64/libcuda.so:/lib64/libcuda.so ghcr.io/huggingface/text-generation-inference:1.3.3 --model-id /data/models--tiiuae--falcon-rw-1b/snapshots/e4b9872bb803165eb22f0a867d4e6a64d34fce19 --num-shard 1 --trust-remote-code --max-input-length 1024 --max-total-tokens 2048 --max-batch-prefill-tokens 2048 --max-concurrent-requests 256 --cuda-memory-fraction 0.04`
2. Rerun the first command, the container will crash as it runs out of CUDA memory

**Comment by Narsil** [comment] 2024-01-16 11:37
The breaking scenario, is because you're not providiing enough memory for the second model (0.04). OOM errors will spoil the entire cuda driver, and impact every other command on that GPU. That's why we warmup as much as we can, do avoid creating those issues in the first place.

**Comment by thomas-schillaci** [comment] 2024-01-16 14:12
But the second model runs fine with 4% VRAM in this scenario

**Comment by Narsil** [comment] 2024-01-17 13:19
What GPU do you have ? Making a 1B model fit 4% of VRAM seems unlikely.

Why load libcuda onto your docker (seems like it could cause quite a bit of issues, since host != docker image) instead of using the `--gpus all`  flag which is more apprioriate I think ?

Unfortunately I' m not able to reproduce. Here are my commands on my smaller GPU:

```
docker run --gpus all -p 8002:80 -v /data/hub:/data/ ghcr.io/huggingface/text-generation-inference:1.3.4 --cuda-memory-fraction 0.20 --model-id tiiuae/falcon-rw-1b --trust-remote-code
docker run --gpus all -p 8000:80 -v /data/hub:/data ghcr.io/huggingface/text-generation-inference:1.3.4 --cuda-mem
ory-fraction 0.80 --model-id bofenghuang/vigostral-7b-chat
```

No matter the order everything is working as expected...

**Comment by thomas-schillaci** [comment] 2024-01-17 14:09
I'm using an A100 80Gb, this model runs well at 4% VRAM.
The shared libcuda is a temporary fix (that I forgot to remove) from when mixtral was released.

Could this problem be caused by using podman instead of docker?
As I can't have docker on this machine, I will try to find a workaround instead.
Thank you for having investigated this issue!

**Comment by thomas-schillaci** [comment] 2024-01-17 15:08
For information, regarding libcuda, I have to keep my fix otherwise I get error:
> Possible files are located at ['/lib64/libcuda.so.1'].Please create a symlink of libcuda.so to any of the file.
2024-01-17T15:06:38.507344Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 95, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 693, in warmup
    _, batch, _ = self.generate_token(batch)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 825, in generate_token
    raise e
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 822, in generate_token
    out = self.forward(batch)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 404, in forward
    logits = self.model.forward(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 843, in forward
    hidden_states = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 789, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 735, in forward
    moe_output = self.moe(normed_attn_res_output)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 586, in forward
    return self.sparse_forward(x)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_mixtral_modeling.py", line 485, in sparse_forward
    x = ops.padded_gather(x, indices, bin_ids, bins, padded_bins, self.top_k)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/stk/backend/autocast.py", line 28, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/megablocks/ops/padded_gather.py", line 14, in forward
    return kernels.padded_gather(
  File "/opt/conda/lib/python3.10/site-packages/megablocks/backend/kernels.py", line 123, in padded_gather
    _padded_copy[(indices.shape[0],)](
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/opt/conda/lib/python3.10/site-packages/triton/testing.py", line 104, in do_bench
    fn()
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 63, in _padded_copy
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler/compiler.py", line 425, in compile
    so_path = make_stub(name, signature, constants)
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler/make_launcher.py", line 39, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/opt/conda/lib/python3.10/site-packages/triton/common/build.py", line 61, in _build
    cuda_lib_dirs = libcuda_dirs()
  File "/opt/conda/lib/python3.10/site-packages/triton/common/build.py", line 30, in libcuda_dirs
    assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg
AssertionError: libcuda.so cannot found!
Possible files are located at ['/lib64/libcuda.so.1'].Please create a symlink of libcuda.so to any of the file.

**Comment by Narsil** [comment] 2024-01-18 11:36
> Could this problem be caused by using podman instead of docker?

Most definitely. Sorry I'm not too knowledgeable with podman, but the way the container sees the GPU is most definitely a potential culprit.

The fact that you need to link libcuda definitely seems to point to something like this. 
This might help: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html

**Comment by Narsil** [comment] 2024-01-18 11:37
I will go ahead and close this issue, you can reopen one specifically for podman if you want, although we do not provide full support for podman it might help others too.

**Closed by Narsil** 2024-01-18 11:37 UTC

**Comment by thomas-schillaci** [comment] 2024-01-18 15:06
Thank you for your help!
