### ISSUE TITLE
RuntimeError: weight model.layers.30.mlp.up_proj.weight does not exist

### ISSUE THREAD

**Issue by xzzWZY** [huggingface/text-generation-inference#730] opened 2023-07-28 16:01 UTC
### System Info

cargo 1.70.0 (ec8a8a0ca 2023-04-25)

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          On   | 00000000:08:00.0 Off |                    0 |
|  0%   27C    P8    32W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A40          On   | 00000000:0B:00.0 Off |                    0 |
|  0%   26C    P8    30W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A40          On   | 00000000:88:00.0 Off |                    0 |
|  0%   25C    P8    29W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A40          On   | 00000000:8C:00.0 Off |                    0 |
|  0%   26C    P8    32W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

running with command 
```
docker run --gpus all --shm-size 1g -p 8080:80 -v /weights:/weights ghcr.io/huggingface/text-generation-inference:0.9.3 --model-id /weights/metaai/llama-13B
```

where /weights/metaai/llama-13B is directly convert from raw weights provided by metaai through scripts in [https://github.com/facebookresearch/llama-recipes/#model-conversion-to-hugging-face](url)

### Expected behavior

I expect it works well, but got issue:

> RuntimeError: weight model.layers.30.mlp.up_proj.weight does not exist

While I "fix" it by using earier version "0.8.2" or "0.8", what may be the problem?

**Comment by Narsil** [comment] 2023-08-02 17:32
Hi.

The missing weights seem like a pretty big issue... 
https://huggingface.co/meta-llama/Llama-2-13b-hf/blob/main/config.json 13B has 40 layers... therefore this weight on layer 30 should exist.

If you could upload the model (or a dummy one showcasing the issue) I could take a look, but it definitely seems like an issue in the weights you provide.

If you check out here: https://huggingface.co/meta-llama/Llama-2-13b-hf?show_tensors=true you'll see that the weight in question is definitely expected.

**Comment by Narsil** [comment] 2023-08-02 17:33
Hi.

The missing weights seem like a pretty big issue... 
https://huggingface.co/meta-llama/Llama-2-13b-hf/blob/main/config.json 13B has 40 layers... therefore this weight on layer 30 should exist.

If you could upload the model (or a dummy one showcasing the issue) I could take a look, but it definitely seems like an issue in the weights you provide.

If you check out here: https://huggingface.co/meta-llama/Llama-2-13b-hf?show_tensors=true you'll see that the weight in question is definitely expected.

Closing for now as it seems the model is really having an issue, please respond or comment here once you have a reproducible script showcasing how the issue is actually within TGI.

Cheers !

**Closed by Narsil** 2023-08-02 17:33 UTC
